/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import exceptions.InvalidNameException;
import exceptions.InvalidPostalCodeException;
import model.validations.UserDataValidations;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author mateoamagra
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     * @throws java.io.FileNotFoundException
     */
    public JFrameMain() throws FileNotFoundException {
        initComponents();
        initConfig();
        //ClassFichero.createFile("C:\\Users\\mateoamagra\\csv\\user_data_MAD.csv");
        //ClassFichero.createFile("C:\\Users\\mateo\\Documents\\csv\\user_data_MAD.csv");
    }

    /**
     * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelErrorName = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jLabelName1 = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelZip = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldBirthDate = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldZip = new javax.swing.JTextField();
        jLabelErrorNIF = new javax.swing.JLabel();
        jLabelErrorBirthDate = new javax.swing.JLabel();
        jLabelErrorEmail = new javax.swing.JLabel();
        jLabelErrorZip = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        jLabelAge = new javax.swing.JLabel();
        jLabelCalcAge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelTitulo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTitulo.setText("Validador datos de usuarios");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/media/imagen.png"))); // NOI18N

        jLabelNIF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNIF.setText("NIF:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelErrorName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelErrorName.setForeground(new java.awt.Color(255, 0, 0));

        jButtonValidar.setBackground(new java.awt.Color(0, 153, 0));
        jButtonValidar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonValidar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jLabelName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelName1.setText("Nombre:");

        jLabelBirthDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBirthDate.setText("Fecha de Nacimiento:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelZip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelZip.setText("Codigo Postal:");

        jTextFieldNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIFActionPerformed(evt);
            }
        });

        jTextFieldBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthDateActionPerformed(evt);
            }
        });

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jTextFieldZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZipActionPerformed(evt);
            }
        });

        jLabelErrorNIF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorNIF.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorNIF.setText(" ");

        jLabelErrorBirthDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorBirthDate.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorEmail.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorZip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorZip.setForeground(new java.awt.Color(255, 0, 0));

        jButtonClear.setBackground(new java.awt.Color(255, 0, 0));
        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCSV.setBackground(new java.awt.Color(51, 255, 255));
        jButtonCSV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCSV.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        jLabelAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAge.setText("Edad Calculada:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelBirthDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCalcAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addComponent(jTextFieldNIF)
                                .addComponent(jTextFieldBirthDate)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jTextFieldZip)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelErrorNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jLabelErrorBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelErrorZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButtonValidar)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonClear)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCSV)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelTitulo)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName1)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelErrorNIF))
                            .addComponent(jLabelNIF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBirthDate)
                                    .addComponent(jTextFieldBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZip)
                    .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorZip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCalcAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidar)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCSV))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initConfig(){
        jButtonValidar.setEnabled(true);
        jButtonClear.setEnabled(true);
        jButtonCSV.setEnabled(false);

        jTextFieldName.setEditable(true);
        jTextFieldNIF.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldZip.setEditable(true);
        jTextFieldBirthDate.setEditable(true);
        
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldZip.setText("");
        jTextFieldBirthDate.setText("");
            
        setLocationRelativeTo(null);              
    }

    
    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        
        int cant = 5;
        
        String name =  jTextFieldName.getText();
//        if (!UserDataValidations.checkName(name)) {
//            jLabelErrorName.setText("nombre incorrecto!");   
//            cant--;
//        }
        
        
        String NIF =  jTextFieldNIF.getText();
        if (!UserDataValidations.checkId(1,NIF)) {
            jLabelErrorNIF.setText("NIF incorrecto!");
            cant--;
        }
        
        String BirthdDate = jTextFieldBirthDate.getText();
        if (!UserDataValidations.checkFormatDate(BirthdDate)) {
            jLabelErrorBirthDate.setText("Fecha invalida");
            cant--;
        }
        
        String mail = jTextFieldEmail.getText();
        if (!UserDataValidations.checkEmail(mail)) {
            jLabelErrorEmail.setText("Mail invalido");
            cant--;
        }
        
        String postal = jTextFieldZip.getText();
//        if (!UserDataValidations.checkPostalCode(postal)) {
//            jLabelErrorZip.setText("Codigo Postal invalido");
//            cant--;
//        }
        
        String age = Integer.toString(UserDataValidations.calculateAge(BirthdDate));
        
        if (cant==5) {
            jButtonValidar.setEnabled(false);
            jButtonCSV.setEnabled(true);
            jLabelCalcAge.setText(age);
        }
        
        try {
            UserDataValidations.checkName(name);
            UserDataValidations.checkPostalCode(postal);
        } catch (InvalidNameException e) {
            jLabelErrorName.setText("nombre incorrecto!");   
        } catch (InvalidPostalCodeException e) {
            jLabelErrorZip.setText("Codigo Postal invalido");

        }
              
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jTextFieldNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIFActionPerformed

    private void jTextFieldBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthDateActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZipActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldZip.setText("");
        jTextFieldBirthDate.setText("");
        jLabelCalcAge.setText("");
        
        
        jLabelErrorName.setText("");
        jLabelErrorNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelErrorBirthDate.setText("");
        jLabelErrorZip.setText("");
        
        jButtonCSV.setEnabled(false);
        jButtonValidar.setEnabled(true);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        // TODO add your handling code here:
        String name =  jTextFieldName.getText();
        String nif =  jTextFieldNIF.getText();
        String fecha_nac =  jTextFieldBirthDate.getText();
        String mail =  jTextFieldEmail.getText();
        String cod_post =  jTextFieldZip.getText();
        String edad =  jLabelCalcAge.getText();
        
        String[] datos = {name, nif, mail, fecha_nac, edad, cod_post};
        String line = String.join(",", datos) + "\n";
        
        ClassFichero.writeFile(line);
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.", "Registro", JOptionPane.INFORMATION_MESSAGE);
        
        jButtonCSV.setEnabled(false);
        
        //pedirle a oriol que me explique lo de la ruta
    }//GEN-LAST:event_jButtonCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameMain().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelCalcAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorBirthDate;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorNIF;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorZip;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelZip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldZip;
    // End of variables declaration//GEN-END:variables
}
